-- FontAwesome Complete Free Icons SQL Script for pgAdmin4
-- This script inserts all FontAwesome free icons with categories into the icon_options table

-- First, ensure the table exists (uncomment if needed)
-- CREATE TABLE IF NOT EXISTS icon_options (
--   id SERIAL PRIMARY KEY,
--   icon_class VARCHAR(100) NOT NULL,
--   icon_name VARCHAR(100) NOT NULL,
--   category VARCHAR(50) NOT NULL
-- );

-- Clear existing data (optional - uncomment if you want to start fresh)
-- TRUNCATE TABLE icon_options RESTART IDENTITY;

-- Insert all FontAwesome free icons with categories
INSERT INTO icon_options (icon_class, icon_name, category) VALUES
-- UI & Navigation Icons
('fa-address-book', 'Address Book', 'UI & Navigation'),
('fa-address-card', 'Address Card', 'UI & Navigation'),
('fa-adjust', 'Adjust', 'UI & Navigation'),
('fa-align-center', 'Align Center', 'UI & Navigation'),
('fa-align-justify', 'Align Justify', 'UI & Navigation'),
('fa-align-left', 'Align Left', 'UI & Navigation'),
('fa-align-right', 'Align Right', 'UI & Navigation'),
('fa-arrow-down', 'Arrow Down', 'UI & Navigation'),
('fa-arrow-left', 'Arrow Left', 'UI & Navigation'),
('fa-arrow-right', 'Arrow Right', 'UI & Navigation'),
('fa-arrow-up', 'Arrow Up', 'UI & Navigation'),
('fa-arrows-alt', 'Arrows Alt', 'UI & Navigation'),
('fa-arrows-alt-h', 'Arrows Alt Horizontal', 'UI & Navigation'),
('fa-arrows-alt-v', 'Arrows Alt Vertical', 'UI & Navigation'),
('fa-asterisk', 'Asterisk', 'UI & Navigation'),
('fa-at', 'At', 'UI & Navigation'),
('fa-backspace', 'Backspace', 'UI & Navigation'),
('fa-bars', 'Bars', 'UI & Navigation'),
('fa-bold', 'Bold', 'UI & Navigation'),
('fa-caret-down', 'Caret Down', 'UI & Navigation'),
('fa-caret-left', 'Caret Left', 'UI & Navigation'),
('fa-caret-right', 'Caret Right', 'UI & Navigation'),
('fa-caret-up', 'Caret Up', 'UI & Navigation'),
('fa-check', 'Check', 'UI & Navigation'),
('fa-check-circle', 'Check Circle', 'UI & Navigation'),
('fa-check-square', 'Check Square', 'UI & Navigation'),
('fa-circle', 'Circle', 'UI & Navigation'),
('fa-circle-notch', 'Circle Notch', 'UI & Navigation'),
('fa-clipboard', 'Clipboard', 'UI & Navigation'),
('fa-clock', 'Clock', 'UI & Navigation'),
('fa-clone', 'Clone', 'UI & Navigation'),
('fa-columns', 'Columns', 'UI & Navigation'),
('fa-copy', 'Copy', 'UI & Navigation'),
('fa-edit', 'Edit', 'UI & Navigation'),
('fa-ellipsis-h', 'Ellipsis Horizontal', 'UI & Navigation'),
('fa-ellipsis-v', 'Ellipsis Vertical', 'UI & Navigation'),
('fa-envelope', 'Envelope', 'UI & Navigation'),
('fa-exclamation', 'Exclamation', 'UI & Navigation'),
('fa-exclamation-circle', 'Exclamation Circle', 'UI & Navigation'),
('fa-exclamation-triangle', 'Exclamation Triangle', 'UI & Navigation'),
('fa-file', 'File', 'UI & Navigation'),
('fa-folder', 'Folder', 'UI & Navigation'),
('fa-font', 'Font', 'UI & Navigation'),
('fa-heading', 'Heading', 'UI & Navigation'),
('fa-home', 'Home', 'UI & Navigation'),
('fa-image', 'Image', 'UI & Navigation'),
('fa-indent', 'Indent', 'UI & Navigation'),
('fa-italic', 'Italic', 'UI & Navigation'),
('fa-link', 'Link', 'UI & Navigation'),
('fa-list', 'List', 'UI & Navigation'),
('fa-minus', 'Minus', 'UI & Navigation'),
('fa-minus-circle', 'Minus Circle', 'UI & Navigation'),
('fa-minus-square', 'Minus Square', 'UI & Navigation'),
('fa-paperclip', 'Paperclip', 'UI & Navigation'),
('fa-paste', 'Paste', 'UI & Navigation'),
('fa-plus', 'Plus', 'UI & Navigation'),
('fa-plus-circle', 'Plus Circle', 'UI & Navigation'),
('fa-plus-square', 'Plus Square', 'UI & Navigation'),
('fa-print', 'Print', 'UI & Navigation'),
('fa-question', 'Question', 'UI & Navigation'),
('fa-question-circle', 'Question Circle', 'UI & Navigation'),
('fa-search', 'Search', 'UI & Navigation'),
('fa-sort', 'Sort', 'UI & Navigation'),
('fa-square', 'Square', 'UI & Navigation'),
('fa-star', 'Star', 'UI & Navigation'),
('fa-times', 'Times', 'UI & Navigation'),
('fa-times-circle', 'Times Circle', 'UI & Navigation'),
('fa-trash', 'Trash', 'UI & Navigation'),
('fa-undo', 'Undo', 'UI & Navigation'),
('fa-user', 'User', 'UI & Navigation'),
('fa-users', 'Users', 'UI & Navigation'),
-- Business & Commerce Icons
('fa-archive', 'Archive', 'Business & Commerce'),
('fa-briefcase', 'Briefcase', 'Business & Commerce'),
('fa-building', 'Building', 'Business & Commerce'),
('fa-calculator', 'Calculator', 'Business & Commerce'),
('fa-chart-bar', 'Chart Bar', 'Business & Commerce'),
('fa-chart-line', 'Chart Line', 'Business & Commerce'),
('fa-chart-pie', 'Chart Pie', 'Business & Commerce'),
('fa-credit-card', 'Credit Card', 'Business & Commerce'),
('fa-dollar-sign', 'Dollar Sign', 'Business & Commerce'),
('fa-euro-sign', 'Euro Sign', 'Business & Commerce'),
('fa-file-invoice', 'File Invoice', 'Business & Commerce'),
('fa-handshake', 'Handshake', 'Business & Commerce'),
('fa-industry', 'Industry', 'Business & Commerce'),
('fa-money-bill', 'Money Bill', 'Business & Commerce'),
('fa-percent', 'Percent', 'Business & Commerce'),
('fa-piggy-bank', 'Piggy Bank', 'Business & Commerce'),
('fa-receipt', 'Receipt', 'Business & Commerce'),
('fa-shopping-cart', 'Shopping Cart', 'Business & Commerce'),
('fa-store', 'Store', 'Business & Commerce'),
('fa-tags', 'Tags', 'Business & Commerce'),
('fa-trophy', 'Trophy', 'Business & Commerce'),
('fa-wallet', 'Wallet', 'Business & Commerce'),
-- Communication & Media Icons
('fa-bell', 'Bell', 'Communication & Media'),
('fa-comment', 'Comment', 'Communication & Media'),
('fa-comments', 'Comments', 'Communication & Media'),
('fa-envelope-open', 'Envelope Open', 'Communication & Media'),
('fa-phone', 'Phone', 'Communication & Media'),
('fa-rss', 'RSS', 'Communication & Media'),
('fa-share', 'Share', 'Communication & Media'),
('fa-video', 'Video', 'Communication & Media'),
('fa-volume-down', 'Volume Down', 'Communication & Media'),
('fa-volume-up', 'Volume Up', 'Communication & Media'),
-- Technology & Devices Icons
('fa-desktop', 'Desktop', 'Technology & Devices'),
('fa-laptop', 'Laptop', 'Technology & Devices'),
('fa-mobile-alt', 'Mobile', 'Technology & Devices'),
('fa-tablet-alt', 'Tablet', 'Technology & Devices'),
('fa-tv', 'TV', 'Technology & Devices'),
('fa-wifi', 'WiFi', 'Technology & Devices'),
('fa-database', 'Database', 'Technology & Devices'),
('fa-microchip', 'Microchip', 'Technology & Devices'),
('fa-server', 'Server', 'Technology & Devices'),
('fa-terminal', 'Terminal', 'Technology & Devices'),
('fa-code', 'Code', 'Technology & Devices'),
('fa-bug', 'Bug', 'Technology & Devices'),
('fa-tools', 'Tools', 'Technology & Devices'),
('fa-wrench', 'Wrench', 'Technology & Devices'),
-- Transportation & Travel Icons
('fa-ambulance', 'Ambulance', 'Transportation & Travel'),
('fa-bicycle', 'Bicycle', 'Transportation & Travel'),
('fa-bus', 'Bus', 'Transportation & Travel'),
('fa-car', 'Car', 'Transportation & Travel'),
('fa-plane', 'Plane', 'Transportation & Travel'),
('fa-ship', 'Ship', 'Transportation & Travel'),
('fa-taxi', 'Taxi', 'Transportation & Travel'),
('fa-train', 'Train', 'Transportation & Travel'),
('fa-truck', 'Truck', 'Transportation & Travel'),
('fa-motorcycle', 'Motorcycle', 'Transportation & Travel'),
('fa-rocket', 'Rocket', 'Transportation & Travel'),
('fa-space-shuttle', 'Space Shuttle', 'Transportation & Travel'),
-- Health & Medical Icons
('fa-heart', 'Heart', 'Health & Medical'),
('fa-heartbeat', 'Heartbeat', 'Health & Medical'),
('fa-medkit', 'Medkit', 'Health & Medical'),
('fa-stethoscope', 'Stethoscope', 'Health & Medical'),
('fa-user-md', 'User MD', 'Health & Medical'),
('fa-hospital', 'Hospital', 'Health & Medical'),
('fa-pills', 'Pills', 'Health & Medical'),
('fa-thermometer', 'Thermometer', 'Health & Medical'),
('fa-tooth', 'Tooth', 'Health & Medical'),
-- Education & Learning Icons
('fa-book', 'Book', 'Education & Learning'),
('fa-graduation-cap', 'Graduation Cap', 'Education & Learning'),
('fa-school', 'School', 'Education & Learning'),
('fa-university', 'University', 'Education & Learning'),
('fa-chalkboard', 'Chalkboard', 'Education & Learning'),
('fa-pencil-alt', 'Pencil Alt', 'Education & Learning'),
('fa-ruler', 'Ruler', 'Education & Learning'),
-- Entertainment & Gaming Icons
('fa-gamepad', 'Gamepad', 'Entertainment & Gaming'),
('fa-music', 'Music', 'Entertainment & Gaming'),
('fa-play', 'Play', 'Entertainment & Gaming'),
('fa-pause', 'Pause', 'Entertainment & Gaming'),
('fa-stop', 'Stop', 'Entertainment & Gaming'),
('fa-film', 'Film', 'Entertainment & Gaming'),
('fa-camera', 'Camera', 'Entertainment & Gaming'),
('fa-headphones', 'Headphones', 'Entertainment & Gaming'),
('fa-microphone', 'Microphone', 'Entertainment & Gaming'),
-- Food & Dining Icons
('fa-utensils', 'Utensils', 'Food & Dining'),
('fa-coffee', 'Coffee', 'Food & Dining'),
('fa-beer', 'Beer', 'Food & Dining'),
('fa-wine-glass', 'Wine Glass', 'Food & Dining'),
('fa-pizza-slice', 'Pizza Slice', 'Food & Dining'),
('fa-ice-cream', 'Ice Cream', 'Food & Dining'),
('fa-cookie', 'Cookie', 'Food & Dining'),
('fa-apple-alt', 'Apple Alt', 'Food & Dining'),
-- Nature & Environment Icons
('fa-leaf', 'Leaf', 'Nature & Environment'),
('fa-tree', 'Tree', 'Nature & Environment'),
('fa-seedling', 'Seedling', 'Nature & Environment'),
('fa-sun', 'Sun', 'Nature & Environment'),
('fa-moon', 'Moon', 'Nature & Environment'),
('fa-cloud', 'Cloud', 'Nature & Environment'),
('fa-rain', 'Rain', 'Nature & Environment'),
('fa-snowflake', 'Snowflake', 'Nature & Environment'),
('fa-fire', 'Fire', 'Nature & Environment'),
('fa-water', 'Water', 'Nature & Environment'),
-- Sports & Recreation Icons
('fa-futbol', 'Futbol', 'Sports & Recreation'),
('fa-basketball-ball', 'Basketball Ball', 'Sports & Recreation'),
('fa-baseball-ball', 'Baseball Ball', 'Sports & Recreation'),
('fa-volleyball-ball', 'Volleyball Ball', 'Sports & Recreation'),
('fa-table-tennis', 'Table Tennis', 'Sports & Recreation'),
('fa-dumbbell', 'Dumbbell', 'Sports & Recreation'),
('fa-running', 'Running', 'Sports & Recreation'),
('fa-swimming-pool', 'Swimming Pool', 'Sports & Recreation'),
('fa-skiing', 'Skiing', 'Sports & Recreation'),
('fa-hiking', 'Hiking', 'Sports & Recreation'),
-- Security & Safety Icons
('fa-shield-alt', 'Shield Alt', 'Security & Safety'),
('fa-lock', 'Lock', 'Security & Safety'),
('fa-unlock', 'Unlock', 'Security & Safety'),
('fa-user-shield', 'User Shield', 'Security & Safety'),
('fa-user-secret', 'User Secret', 'Security & Safety'),
('fa-eye', 'Eye', 'Security & Safety'),
('fa-eye-slash', 'Eye Slash', 'Security & Safety'),
('fa-key', 'Key', 'Security & Safety'),
('fa-fingerprint', 'Fingerprint', 'Security & Safety'),
-- Time & Calendar Icons
('fa-calendar', 'Calendar', 'Time & Calendar'),
('fa-calendar-alt', 'Calendar Alt', 'Time & Calendar'),
('fa-clock', 'Clock', 'Time & Calendar'),
('fa-stopwatch', 'Stopwatch', 'Time & Calendar'),
('fa-hourglass', 'Hourglass', 'Time & Calendar'),
('fa-history', 'History', 'Time & Calendar'),
-- Location & Maps Icons
('fa-map', 'Map', 'Location & Maps'),
('fa-map-marker', 'Map Marker', 'Location & Maps'),
('fa-map-pin', 'Map Pin', 'Location & Maps'),
('fa-globe', 'Globe', 'Location & Maps'),
('fa-compass', 'Compass', 'Location & Maps'),
('fa-location-arrow', 'Location Arrow', 'Location & Maps'),
('fa-street-view', 'Street View', 'Location & Maps'),
-- Objects & Tools Icons
('fa-toolbox', 'Toolbox', 'Objects & Tools'),
('fa-hammer', 'Hammer', 'Objects & Tools'),
('fa-screwdriver', 'Screwdriver', 'Objects & Tools'),
('fa-wrench', 'Wrench', 'Objects & Tools'),
('fa-tools', 'Tools', 'Objects & Tools'),
('fa-cog', 'Cog', 'Objects & Tools'),
('fa-cogs', 'Cogs', 'Objects & Tools'),
('fa-microchip', 'Microchip', 'Objects & Tools'),
('fa-bolt', 'Bolt', 'Objects & Tools'),
('fa-plug', 'Plug', 'Objects & Tools'),
('fa-lightbulb', 'Lightbulb', 'Objects & Tools'),
('fa-battery-full', 'Battery Full', 'Objects & Tools'),
('fa-battery-half', 'Battery Half', 'Objects & Tools'),
('fa-battery-empty', 'Battery Empty', 'Objects & Tools'),
-- Social & People Icons
('fa-user', 'User', 'Social & People'),
('fa-users', 'Users', 'Social & People'),
('fa-user-friends', 'User Friends', 'Social & People'),
('fa-user-plus', 'User Plus', 'Social & People'),
('fa-user-minus', 'User Minus', 'Social & People'),
('fa-user-check', 'User Check', 'Social & People'),
('fa-user-times', 'User Times', 'Social & People'),
('fa-user-circle', 'User Circle', 'Social & People'),
('fa-user-graduate', 'User Graduate', 'Social & People'),
('fa-user-tie', 'User Tie', 'Social & People'),
('fa-user-ninja', 'User Ninja', 'Social & People'),
('fa-user-astronaut', 'User Astronaut', 'Social & People'),
('fa-child', 'Child', 'Social & People'),
('fa-baby', 'Baby', 'Social & People'),
('fa-male', 'Male', 'Social & People'),
('fa-female', 'Female', 'Social & People'),
('fa-user-md', 'User MD', 'Social & People'),
('fa-user-nurse', 'User Nurse', 'Social & People'),
('fa-user-graduate', 'User Graduate', 'Social & People'),
('fa-user-injured', 'User Injured', 'Social & People'),
-- Miscellaneous Icons
('fa-anchor', 'Anchor', 'Miscellaneous'),
('fa-archive', 'Archive', 'Miscellaneous'),
('fa-award', 'Award', 'Miscellaneous'),
('fa-ban', 'Ban', 'Miscellaneous'),
('fa-bell', 'Bell', 'Miscellaneous'),
('fa-bell-slash', 'Bell Slash', 'Miscellaneous'),
('fa-birthday-cake', 'Birthday Cake', 'Miscellaneous'),
('fa-bomb', 'Bomb', 'Miscellaneous'),
('fa-bookmark', 'Bookmark', 'Miscellaneous'),
('fa-briefcase', 'Briefcase', 'Miscellaneous'),
('fa-bug', 'Bug', 'Miscellaneous'),
('fa-bullhorn', 'Bullhorn', 'Miscellaneous'),
('fa-bullseye', 'Bullseye', 'Miscellaneous'),
('fa-certificate', 'Certificate', 'Miscellaneous'),
('fa-crown', 'Crown', 'Miscellaneous'),
('fa-diamond', 'Diamond', 'Miscellaneous'),
('fa-gem', 'Gem', 'Miscellaneous'),
('fa-gift', 'Gift', 'Miscellaneous'),
('fa-heart', 'Heart', 'Miscellaneous'),
('fa-heart-broken', 'Heart Broken', 'Miscellaneous'),
('fa-magic', 'Magic', 'Miscellaneous'),
('fa-medal', 'Medal', 'Miscellaneous'),
('fa-palette', 'Palette', 'Miscellaneous'),
('fa-puzzle-piece', 'Puzzle Piece', 'Miscellaneous'),
('fa-ribbon', 'Ribbon', 'Miscellaneous'),
('fa-star', 'Star', 'Miscellaneous'),
('fa-star-half', 'Star Half', 'Miscellaneous'),
('fa-thumbs-up', 'Thumbs Up', 'Miscellaneous'),
('fa-thumbs-down', 'Thumbs Down', 'Miscellaneous'),
('fa-trophy', 'Trophy', 'Miscellaneous'),
('fa-umbrella', 'Umbrella', 'Miscellaneous'),
('fa-wine-glass', 'Wine Glass', 'Miscellaneous');

-- Success message
SELECT 'FontAwesome icons with categories inserted successfully!' as message; 